FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src

ARG JWT_SECRET
ENV JWT_SECRET=$JWT_SECRET

ARG STEAM_API_KEY
ENV STEAM_API_KEY=$STEAM_API_KEY

ARG DISCORD_WEBHOOK_URL
ENV DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL

ARG DB_HOST
ENV DB_HOST=$DB_HOST

ARG DB_PORT
ENV DB_PORT=$DB_PORT

ARG DB_USER
ENV DB_USER=$DB_USER

ARG DB_PASS
ENV DB_PASS=$DB_PASS

ARG SPRING_PROFILES_ACTIVE
ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE

ARG PASS_CERT_BACK
ENV PASS_CERT_BACK=$PASS_CERT_BACK

RUN mvn package

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

RUN apk update && apk upgrade

COPY --from=build app/target/steam-family-manager-0.0.1-SNAPSHOT.jar .

ARG JWT_SECRET
ENV JWT_SECRET=$JWT_SECRET

ARG STEAM_API_KEY
ENV STEAM_API_KEY=$STEAM_API_KEY

ARG DISCORD_WEBHOOK_URL
ENV DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL

ARG DB_HOST
ENV DB_HOST=$DB_HOST

ARG DB_PORT
ENV DB_PORT=$DB_PORT

ARG DB_USER
ENV DB_USER=$DB_USER

ARG DB_PASS
ENV DB_PASS=$DB_PASS

ARG SPRING_PROFILES_ACTIVE
ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE

ARG PASS_CERT_BACK
ENV PASS_CERT_BACK=$PASS_CERT_BACK

EXPOSE 8080

CMD ["java", "-jar", "steam-family-manager-0.0.1-SNAPSHOT.jar"]
