spring.application.name=Steam Family Manager

# Steam API
steam.api.key=${STEAM_API_KEY}
steam.api.base-url=https://api.steampowered.com

# Discord
discord.webhook.url=${DISCORD_WEBHOOK_URL}

# JWT
steam.auth.jwt.secret=${JWT_SECRET}

# Game Sync (5 minutes)
game.sync.fixed-rate=300000

# Health Check
management.endpoints.web.exposure.include=health
